import {logger} from "firebase-functions/v2";
import moment from "moment-timezone";
// eslint-disable-next-line camelcase
import {google, calendar_v3, Auth} from "googleapis";
import handleAsync from "../../util/handleAsync";
import {getOauthClient} from "../../auth/authHandler";
import ical from "node-ical";
import _ from "underscore";
import {sendEvent} from "../../util/analytics";
import {MAIN_EMAIL_ADDRESS, DEFAULT_EVENT_LENGTH_MINUTES} from "../../util/config";
import {
  Event,
  GoogleCalendar,
  MappedCalendar,
  CalendarForLLM,
  GoogleCalendarEvent,
  TimeObject,
  ParsedICSEvent,
  ICSFile,
  CalendarEventRequestBody,
  ICalEvent,
  ICalTimezone,
} from "./types";
import {RequestWithQuery} from "../../util/types";
import {Response} from "express";

const ONLY_INVITE_HOST = true;

function generateTimeObject(
    event: Event,
    primaryCalendar: GoogleCalendar | MappedCalendar,
    uid: string,
): TimeObject {
  const timezone = primaryCalendar.timeZone;
  let eventTimeZone = event.timeZone || timezone;
  logger.debug(
      `Calendar timezone: ${timezone}, eventTimezone: ${eventTimeZone}`,
  );
  try {
    new Intl.DateTimeFormat(undefined, {timeZone: eventTimeZone});
  } catch {
    console.error("Invalid Time Zone in event object:", eventTimeZone);
    sendEvent(uid, "dataQualityIssue", {reason: "invalid_timezone"});
    // Fallback to primary calendar's timezone if event's timezone is invalid
    eventTimeZone = timezone;
  }
  // eslint-disable-next-line camelcase
  const {date, start_time, end_time} = event;
  const startTime = `${date} ${start_time}`; // eslint-disable-line camelcase
  const startDate = moment
      .tz(startTime, "DD MMMM YYYY HH:mm", eventTimeZone)
      .toDate();
  const endTime = `${date} ${end_time}`; // eslint-disable-line camelcase
  const defaultEventLength = parseInt(DEFAULT_EVENT_LENGTH_MINUTES.value());
  let endDate: Date;
  // eslint-disable-next-line camelcase
  if (end_time) {
    try {
      endDate = moment.tz(endTime, "DD MMMM YYYY HH:mm", eventTimeZone).toDate();
      if (isNaN(endDate.getTime())) {
        throw new Error("Invalid end time");
      }
    } catch (_error) {
      sendEvent(uid, "dataQualityIssue", {reason: "invalid_end_time"});
      // Default to configured event length
      endDate = new Date(startDate.getTime() + defaultEventLength * 60000);
    }
  } else {
    // Default to configured event length
    endDate = new Date(startDate.getTime() + defaultEventLength * 60000);
  }
  const timeObject: TimeObject = {
    start: {
      dateTime: startDate.toISOString(),
      timeZone: eventTimeZone,
    },
    end: {
      dateTime: endDate.toISOString(),
      timeZone: eventTimeZone,
    },
  };
  return timeObject;
}

async function addEvent(
    oauth2Client: Auth.OAuth2Client,
    event: Event,
    uid: string,
): Promise<GoogleCalendarEvent> {
  const calendar = google.calendar({version: "v3", auth: oauth2Client});
  const calendarList = await calendar.calendarList.list();
  const primaryCalendar = calendarList.data.items?.find(
      (cal) => cal.primary,
  ) as GoogleCalendar | undefined;
  if (!primaryCalendar) {
    sendEvent(uid, "calendarError", {reason: "no_primary_calendar"});
    throw new Error("Primary calendar not found");
  }

  // Determine target calendar: use selected_calendar_id if provided, otherwise use primary
  let targetCalendar: GoogleCalendar = primaryCalendar;
  if (event.selected_calendar_id) {
    const selectedCal = calendarList.data.items?.find(
        (cal) => cal.id === event.selected_calendar_id,
    ) as GoogleCalendar | undefined;
    if (selectedCal) {
      targetCalendar = selectedCal;
      logger.log(`Using selected calendar: ${targetCalendar.id}`);
    } else {
      logger.warn(
          `Selected calendar ${event.selected_calendar_id} not found, using primary`,
      );
    }
  }

  const times = generateTimeObject(event, targetCalendar, uid);
  let eventDescription = event.description;
  if (eventDescription === undefined || eventDescription === "undefined") {
    eventDescription = "";
  }
  eventDescription = `${eventDescription}
\n\nThis event was generated by AI with fwd2cal.com.
\nDon't waste time creating events, just forward them to ${MAIN_EMAIL_ADDRESS.value()}.`;

  const requestBody: CalendarEventRequestBody = {
    summary: event.summary,
    status: "confirmed",
    description: eventDescription,
    attendees: event.attendees.map((attendee) => ({email: attendee})),
    start: times.start,
    end: times.end,
    guestsCanInviteOthers: true,
    guestsCanModify: true,
    guestsCanSeeOtherGuests: true,
  };
  if (event.location) {
    requestBody.location = event.location;
  }

  // This is needs a refactor.
  if (ONLY_INVITE_HOST) {
    requestBody.attendees = [
      {email: targetCalendar.id, responseStatus: "accepted"},
    ];
  }
  logger.log("Attempting to add event to google.");

  const maxRetries = 1;
  const retryDelay = 1000; // 1 second
  // eslint-disable-next-line camelcase
  let insertEvent: calendar_v3.Schema$Event | undefined;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await calendar.events.insert({
        calendarId: targetCalendar.id,
        conferenceDataVersion: 1,
        // eslint-disable-next-line camelcase
        requestBody: requestBody as calendar_v3.Schema$Event,
        sendNotifications: true,
        sendUpdates: "all",
      });
      insertEvent = response.data;
      logger.log("Event added to google.", insertEvent.htmlLink);
      break; // Success, exit retry loop
    } catch (error) {
      const err = error as {
        code?: string;
        message?: string;
        response?: { status: number };
      };
      const isRetriableError =
        err.code === "ECONNRESET" ||
        err.code === "ETIMEDOUT" ||
        err.message?.includes("socket hang up") ||
        err.message?.includes("timeout") ||
        (err.message?.includes("The specified time range is empty") === false &&
          err.response &&
          err.response.status >= 500);

      if (attempt < maxRetries && isRetriableError) {
        const attemptNum = attempt + 1;
        const totalAttempts = maxRetries + 1;
        logger.warn(
            `Calendar API error (attempt ${attemptNum}/${totalAttempts}): ${err.message}. Retrying...`,
        );
        await new Promise((resolve) => setTimeout(resolve, retryDelay));
      } else {
        logger.error("Calendar API error (final attempt):", err.message);
        if (isRetriableError) {
          // Network/timeout error that failed after retries
          sendEvent(uid, "calendarError", {
            reason: "api_error",
            error_type: err.code || "unknown",
          });
        } else {
          // Validation or other non-retriable error
          sendEvent(uid, "calendarError", {reason: "validation_error"});
        }
        throw error; // Re-throw the error after max retries or non-retriable error
      }
    }
  }

  if (!insertEvent) {
    throw new Error("Failed to insert event after retries");
  }

  sendEvent(uid, "addEvent", {result: "success"});

  const result: GoogleCalendarEvent = {
    kind: "calendar#event",
    id: insertEvent.id || "",
    htmlLink: insertEvent.htmlLink || "",
    summary: insertEvent.summary || "",
    description: insertEvent.description,
    start: {
      dateTime: insertEvent.start?.dateTime || "",
      timeZone: insertEvent.start?.timeZone || "",
    },
    end: {
      dateTime: insertEvent.end?.dateTime || "",
      timeZone: insertEvent.end?.timeZone || "",
    },
    attendees: insertEvent.attendees?.map((a) => ({
      email: a.email || "",
      responseStatus: a.responseStatus,
    })),
    organizer: insertEvent.organizer ?
      {
        email: insertEvent.organizer.email || "",
        displayName: insertEvent.organizer.displayName,
      } :
      undefined,
    location: insertEvent.location,
    calendarId: targetCalendar.id,
    calendarName: targetCalendar.summary,
    isPrimaryCalendar: targetCalendar.primary || false,
    uid: uid,
  };

  return result;
}

async function eventFromICS(icsFile: ICSFile): Promise<ParsedICSEvent> {
  const icsString = Buffer.from(icsFile.file).toString("utf-8");
  const ics = await ical.async.parseICS(icsString);
  const timezones = _.select(_.values(ics) as ICalTimezone[], (x) => {
    return x.type === "VTIMEZONE";
  });
  if (timezones.length > 1) {
    throw new Error("Multiple timezones found, too complicated.");
  }
  let timezone: string | undefined;
  if (timezones.length !== 0) {
    timezone = timezones[0].tzid;
  }
  const events = _.select(_.values(ics) as ICalEvent[], (x) => {
    return x.type === "VEVENT";
  });
  if (events.length > 1) {
    throw new Error("Multiple events found, too complicated.");
  }
  const event = events[0];
  if (!event) {
    throw new Error("Event not found");
  }

  const tz = timezone || "UTC";
  const start = moment(event.start).tz(tz).format("HH:mm");
  const end = moment(event.end).tz(tz).format("HH:mm");
  const date = moment(event.start).tz(tz).format("DD MMMM YYYY");

  let summary: string;
  if (event.summary && typeof event.summary === "object" && "val" in event.summary) {
    summary = event.summary.val;
  } else {
    summary = (event.summary as string) || "Event";
  }

  let description: string | undefined;
  if (event.description && typeof event.description === "object" && "val" in event.description) {
    description = event.description.val;
  } else {
    description = event.description as string | undefined;
  }

  let location: string | undefined;
  if (event.location && typeof event.location === "object" && "val" in event.location) {
    location = event.location.val;
  } else {
    location = event.location as string | undefined;
  }

  const attendees: string[] = [];
  if (event.organizer?.val) {
    attendees.push(event.organizer.val.replace("MAILTO:", ""));
  }
  if (event.attendee && event.attendee.length > 0 && event.attendee[0].val) {
    attendees.push(
        ...event.attendee.map((attendee) => attendee.val.replace("MAILTO:", "")),
    );
  }

  const r: ParsedICSEvent = {
    summary: summary,
    location: location,
    description: description,
    conference_call: "",
    date: date,
    start_time: start,
    end_time: end,
    attendees: attendees,
  };
  if (timezone) {
    r.timezone = timezone;
  }
  return r;
}

async function getUserCalendars(
    oauth2Client: Auth.OAuth2Client,
    uid: string,
): Promise<MappedCalendar[]> {
  const calendar = google.calendar({version: "v3", auth: oauth2Client});
  const calendarList = await calendar.calendarList.list();

  // Filter to only writable calendars (owner or writer)
  const calendars: MappedCalendar[] = (calendarList.data.items || [])
      .filter(
          (cal) => cal.accessRole === "owner" || cal.accessRole === "writer",
      )
      .map((cal) => ({
        kind: cal.kind || "",
        etag: cal.etag || "",
        selected: cal.selected,
        accessRole: cal.accessRole || "",
        conferenceProperties: cal.conferenceProperties as
        | { allowedConferenceSolutionTypes: string[] }
        | undefined,
        calendar_id: cal.id || "",
        summary: cal.summary || "",
        summaryOverride: cal.summaryOverride,
        description: cal.description,
        primary: cal.primary,
        timeZone: cal.timeZone || "",
        location: cal.location,
        hidden: cal.hidden,
        deleted: cal.deleted,
        uid: uid,
      }));
  return calendars;
}

/**
 * Formats calendar object for LLM consumption
 * Includes only relevant fields that help LLM choose the right calendar
 */
function formatCalendarForLLM(calendar: MappedCalendar): CalendarForLLM {
  return {
    calendar_id: calendar.calendar_id,
    summary: calendar.summaryOverride || calendar.summary, // Use custom name if set
    description: calendar.description || "", // Calendar description for context
    is_default: calendar.primary === true,
    timeZone: calendar.timeZone,
  };
}

async function inviteAdditionalAttendees(
    req: RequestWithQuery,
    res: Response,
): Promise<Response | void> {
  const {uid, eventId, calendarId} = req.query;
  const attendees = req.query.attendees;
  let attendeesList: string[] = [];

  if (typeof attendees === "string") {
    try {
      attendeesList = JSON.parse(attendees);
    } catch (_error) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(attendees)) {
        console.error(
            "Attendees string is not a valid single email address:",
            attendees,
        );
        return res.status(400).send({
          error: "Attendees string is not a valid single email address.",
        });
      } else {
        attendeesList = [attendees];
      }
    }
  } else if (Array.isArray(attendees)) {
    attendeesList = attendees;
  }

  if (!uid || !eventId || !calendarId) {
    return res.status(400).send({error: "Missing required parameters"});
  }

  // Can we authenticate with their calendar?
  const [oauthErr, oauth2Client] = await handleAsync(() => getOauthClient(uid));
  if (oauthErr || !oauth2Client) {
    logger.warn("Error getting oauth2Client", oauthErr);
    return res.redirect(302, "https://www.fwd2cal.com/404");
  }
  const calendar = google.calendar({version: "v3", auth: oauth2Client});
  const eventToUpdate = await calendar.events.get({
    calendarId: calendarId,
    eventId: eventId,
  });
  const htmlLink = eventToUpdate.data.htmlLink;
  const attendeesToAdd = attendeesList.map((attendee) => ({
    email: attendee,
  }));
  eventToUpdate.data.attendees = eventToUpdate.data.attendees || [];
  eventToUpdate.data.attendees.push(...attendeesToAdd);
  const updatedEvent = await calendar.events.update({
    calendarId: calendarId,
    eventId: eventId,
    sendNotifications: true,
    sendUpdates: "all",
    conferenceDataVersion: 1,
    requestBody: eventToUpdate.data,
  });
  logger.log(`Event updated with additional guests ${updatedEvent.data.id}`);
  return res.redirect(302, htmlLink || "https://www.fwd2cal.com");
}

export {
  addEvent,
  getUserCalendars,
  formatCalendarForLLM,
  inviteAdditionalAttendees,
  eventFromICS,
  generateTimeObject,
};
