/* eslint-disable max-len */
/* eslint-disable camelcase */
/* eslint-disable new-cap */
/* eslint-disable require-jsdoc */
const {logger} = require("firebase-functions");
const moment = require("moment-timezone");
const {google} = require("googleapis");

const DEFAULT_EVENT_LENGTH = 30;
const ONLY_INVITE_HOST = true;

function generateTimeObject(event, primaryCalendar) {
  // logger.log("event", event);
  const timezone = primaryCalendar.timeZone;
  let eventTimeZone = event.timeZone;
  logger.debug(`Calendar timezone: ${timezone}, eventTimezone: ${eventTimeZone}`);
  if (!Intl.DateTimeFormat(undefined, {timeZone: eventTimeZone})
      .resolvedOptions().timeZone) {
    console.error("Invalid Time Zone in event object:", eventTimeZone);
    // Fallback to primary calendar's timezone if event's timezone is invalid
    eventTimeZone = timezone;
  }
  const {date, start_time, end_time} = event;
  const startTime = `${date} ${start_time}`;
  const startDate = moment.tz(startTime, "DD MMMM YYYY HH:mm", eventTimeZone)
      .toDate();
  const endTime = `${date} ${end_time}`;
  let endDate;
  if (event.end_time) {
    try {
      endDate = moment.tz(endTime, "DD MMMM YYYY HH:mm", eventTimeZone).toDate();
      if (isNaN(endDate.getTime())) {
        throw new Error("Invalid end time");
      }
    } catch (error) {
      // Default 30 minutes to start_time
      endDate = new Date(startDate.getTime() + (DEFAULT_EVENT_LENGTH * 60000));
    }
  } else {
    // Default 30 minutes to start_time
    endDate = new Date(startDate.getTime() + (DEFAULT_EVENT_LENGTH * 60000));
  }
  const timeObject = {
    start: {
      dateTime: startDate.toISOString(),
      timeZone: eventTimeZone,
    },
    end: {
      dateTime: endDate.toISOString(),
      timeZone: eventTimeZone,
    },
  };
  return timeObject;
}

async function addEvent(oauth2Client, event) {
  const calendar = google.calendar({version: "v3", auth: oauth2Client});
  const calendarList = await calendar.calendarList.list();
  const primaryCalendar = calendarList.data.items
      .find((calendar) => calendar.primary);
  if (!primaryCalendar) {
    throw new Error("Primary calendar not found");
  }
  const times = generateTimeObject(event, primaryCalendar);
  if (event.description === undefined || event.description === "undefined") {
    event.description = "";
  }
  event.description = `${event.description} 
\n\nThis event was generated by AI with fwd2cal.com.
\nDon't waste time creating events, just forward them to calendar@fwd2cal.com.`;
  const requestBody = {
    summary: event.summary,
    description: event.description,
    attendees: event.attendees.map((attendee) => ({email: attendee})),
    start: times.start,
    end: times.end,
  };
  if (event.location) {
    requestBody.location = event.location;
  }
  if (ONLY_INVITE_HOST) {
    requestBody.attendees = [
      {email: primaryCalendar.id,
        responseStatus: "accepted"}];
  }
  logger.log("Attempting to add event to google.");
  const insertEvent = await calendar.events.insert({
    calendarId: primaryCalendar.id,
    resource: requestBody,
    sendUpdates: "all",
  });
  logger.log("Event added to google.", insertEvent.data.htmlLink);
  return insertEvent.data;
}

async function getUserCalendars(oauth2Client, uid) {
  const calendar = google.calendar({version: "v3", auth: oauth2Client});
  const calendarList = await calendar.calendarList.list();
  // logger.log("CALENDAR OBJECT FULL:", calendarList);
  const calendars = calendarList.data.items.map((calendar) => ({
    kind: calendar.kind,
    etag: calendar.etag,
    selected: calendar.selected,
    accessRole: calendar.accessRole,
    conferenceProperties: calendar.conferenceProperties,
    calendar_id: calendar.id,
    summary: calendar.summary,
    summaryOverride: calendar.summaryOverride,
    description: calendar.description,
    primary: calendar.primary,
    timeZone: calendar.timeZone,
    location: calendar.location,
    hidden: calendar.hidden,
    deleted: calendar.deleted,
    uid: uid,
  }));
  // logger.log("Calendars:", calendars);
  return calendars;
}

module.exports = {
  addEvent,
  getUserCalendars,
};

